# Generated by Django 5.2.1 on 2025-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.BigIntegerField()),
                ('homepage', models.URLField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(max_length=10)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField()),
                ('tagline', models.TextField(blank=True, null=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('keywords', models.ManyToManyField(to='movies.keyword')),
                ('production_companies', models.ManyToManyField(to='movies.productioncompany')),
                ('production_countries', models.ManyToManyField(to='movies.productioncountry')),
                ('spoken_languages', models.ManyToManyField(to='movies.spokenlanguage')),
            ],
        ),
    ]
