# Generated by Django 5.2.1 on 2025-06-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='keyword',
            table='keyword',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='productioncompany',
            table='production_company',
        ),
        migrations.AlterModelTable(
            name='productioncountry',
            table='production_country',
        ),
        migrations.AlterModelTable(
            name='spokenlanguage',
            table='spoken_language',
        ),
    ]
