# Generated by Django 5.2.1 on 2025-06-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_genre_name_alter_keyword_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_title_5cbe35_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_release_f47371_idx',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productioncountry',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
