# Generated by Django 5.2.1 on 2025-06-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_movie_title_5cbe35_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'adult'], name='movie_title_5da1db_idx'),
        ),
    ]
